New Directory for DSA Problems and first problem
bhushan/preps pull request #1
Opened 2022-06-16 12:53 UTC by sameer03697

2022-06-17 18:32 UTC, bhushan commented
Hi @sameer03697 .. thank you for your PR. I have updated directory structure of the repo. Please create `cpp` folder and root and then put all your changes inside that folder. 

Things to be kept in mind while you refactor,
- we are using `snake-case` for files and directories
- https://github.com/p00f/cphelper.nvim try this plugin and we can use same structure in `cpp` folder
- also for commit messages i am following `[BinaryTree]: Kth sum problem` this kind of pattern, please use this pattern to keep things consistent.

2022-06-17 18:33 UTC, bhushan commented on dsaProblemsCPP/readme.md
> +This is for DSA problems
we dont need readme here

2022-06-17 18:59 UTC, bhushan requested changes

2022-06-17 18:59 UTC, bhushan commented on dsaProblemsCPP/binarySearch/KthSumValue/sol.cpp
> +    /*for(auto i: a){
remove unwanted code

2022-06-17 18:59 UTC, bhushan commented on dsaProblemsCPP/binarySearch/KthSumValue/sol.cpp
> +    //cout<<"I am Sameer Kumar"<<endl;
remove commented code

2022-06-19 05:10 UTC, sameer03697 commented
Did a force push 😢 . Please do a review.

2022-06-19 20:20 UTC, bhushan requested changes
add readme.md with instructions to run programs and install utils. and also change file names to input.txt and solution.cpp

2022-06-25 09:21 UTC, sameer03697 commented
@bhushan Please review this PR

2022-06-25 09:25 UTC, sameer03697 commented
@bhushan Please review this PR.  I willl do Utils for cpp next time.

2022-08-09 02:38 UTC, sameer03697 commented
Added first 18 problems, please review this, I will add more problems soon.

2022-08-15 17:35 UTC, bhushan commented on .gitignore
> +*
please put this file inside cpp folder

2022-08-21 07:15 UTC, merged